name: Generate HTML

on:
  pull_request:
    types: [closed]
  push:
    branches: [ main ]

jobs:
  build:
    # Only run if the PR was merged or if it's a direct push to main
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate HTML
      run: |
        python src/generate.py awesome_3dgs_papers.yaml index.html

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update generated HTML
        title: Update generated HTML
        body: |
          Auto-generated PR to update the HTML based on recent YAML changes.
          
          This PR was automatically created by the Generate HTML workflow.
        branch: update-html
        base: main
        delete-branch: true
