name: Generate HTML

on:
  pull_request:
    types: [closed]
  push:
    branches: [main]

jobs:
  build:
    # Only run if PR was merged and it came from the bot, or if it's a direct push to main
    if: (github.event.pull_request.merged == true && contains(github.event.pull_request.head.ref, 'MrNeRF/bot')) || github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate HTML
      run: |
        python src/generate.py awesome_3dgs_papers.yaml index.html

    - name: Commit and Push if Bot
      if: contains(github.event.pull_request.head.ref, 'MrNeRF/bot')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Configure git
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # Check for changes
        if git diff --quiet index.html; then
          echo "No changes to commit"
          exit 0
        fi
        
        # Commit and push changes directly to main
        git add index.html
        git commit -m "Auto-update index.html based on bot PR merge [skip ci]"
        git push origin main
