name: Generate HTML on Main

on:
  push:
    branches: [ main ]
    paths:
      - 'awesome_3dgs_papers.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.BOT_PAT }}  # Use PAT instead of GITHUB_TOKEN
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate HTML
      run: |
        python src/generate.py awesome_3dgs_papers.yaml index.html

    - name: Commit and push if changed
      run: |
        git config --local user.email "bot@users.noreply.github.com"
        git config --local user.name "Repository Bot"
        git add index.html
        git diff --staged --quiet || (git commit -m "Update index.html" && git push)