name: Generate HTML

on:
  push:
    branches: [ main ]
    paths:
      - 'awesome_3dgs_papers.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate HTML
      run: |
        python src/generate.py awesome_3dgs_papers.yaml index.html

    - name: Commit and Push
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        if ! git diff --quiet index.html; then
          git add index.html
          git commit -m "Auto-update index.html from YAML changes [skip ci]"
          git push origin main
        fi
